/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class Window extends javax.swing.JFrame {

    private Thread zombieThread;
    private boolean zombieMovingRight = true;

    int x;
    int y;

    public Window() {
        initComponents();
        setFocusable(true);
        startZombieMovement();
        x = player.getX();
        y = player.getY();
    }

    private void startZombieMovement() {
        zombieThread = new Thread(() -> {
            while (true) {
                moveZombie();
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        zombieThread.start();
    }

    private void moveZombie() {
        int x = zombie1.getX();
        if (zombieMovingRight) {
            if (x < getWidth() - zombie1.getWidth()) {
                zombie1.setLocation(x + 5, zombie1.getY());
            } else {
                zombieMovingRight = false;
            }
        } else {
            if (x > 0) {
                zombie1.setLocation(x - 5, zombie1.getY());
            } else {
                zombieMovingRight = true;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameover = new javax.swing.JLabel();
        player = new javax.swing.JLabel();
        zombie1 = new javax.swing.JLabel();
        hole2 = new javax.swing.JPanel();
        hole1 = new javax.swing.JPanel();
        stage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/died.png"))); // NOI18N
        getContentPane().add(gameover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/Player.png"))); // NOI18N
        getContentPane().add(player, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        zombie1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/zombie.png"))); // NOI18N
        getContentPane().add(zombie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        hole2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout hole2Layout = new javax.swing.GroupLayout(hole2);
        hole2.setLayout(hole2Layout);
        hole2Layout.setHorizontalGroup(
            hole2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        hole2Layout.setVerticalGroup(
            hole2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(hole2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 70, 60));

        hole1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout hole1Layout = new javax.swing.GroupLayout(hole1);
        hole1.setLayout(hole1Layout);
        hole1Layout.setHorizontalGroup(
            hole1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        hole1Layout.setVerticalGroup(
            hole1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(hole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 220, 60));

        stage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/resources/stage2.png"))); // NOI18N
        getContentPane().add(stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            player.setBounds(x, y, player.getWidth(), player.getHeight());
            y = y - 10;
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            player.setBounds(x, y, player.getWidth(), player.getHeight());
            y = y + 10;
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            player.setBounds(x, y, player.getWidth(), player.getHeight());
            x = x+10;
        }
        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            player.setBounds(x, y, player.getWidth(), player.getHeight());
            x = x-10;
        }

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameover;
    private javax.swing.JPanel hole1;
    private javax.swing.JPanel hole2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel player;
    private javax.swing.JLabel stage;
    private javax.swing.JLabel zombie1;
    // End of variables declaration//GEN-END:variables


}
